Completed task 5. GET /api/articles/:article_id
juliaozm/project-news pull request #4
Opened 2023-01-17 10:24 UTC by juliaozm

Submitting request for task 5

2023-01-17 11:42 UTC, xViolaine requested changes
Good job, just an extra test needed and a small change in the file structure!

2023-01-17 11:42 UTC, xViolaine commented on db/app.js
>  const express = require('express')
Generally speaking, your app.js should live outside of the db folder

2023-01-17 11:42 UTC, xViolaine commented on __tests__/app.test.js
> +        })
We also want to make sure to include a test for a 400 for when a ID is used that will never exist

2023-01-19 12:05 UTC, Hard-Luck approved these changes
Good work, good to merge!

2023-01-19 12:40 UTC, merged