Completed task 7. POST /api/articles/:article_id/comments
juliaozm/project-news pull request #6
Opened 2023-01-18 09:29 UTC by juliaozm

Submitting solution for task 7. POST /api/articles/:article_id/comments

2023-01-18 10:54 UTC, Hard-Luck requested changes

2023-01-18 10:54 UTC, Hard-Luck commented on __tests__/app.test.js
> +        test('POST: 400 - returns a message "Bad request" when a received object is empty', () => {
I would change the wording of this to, request body

2023-01-18 10:54 UTC, Hard-Luck commented on __tests__/app.test.js
> +    })
add a test that tests if the request body has additional keys and that they are ignored

2023-01-18 10:54 UTC, Hard-Luck commented on __tests__/app.test.js
> +    })
Needs a test for if the id in the url is not a number

2023-01-18 10:54 UTC, Hard-Luck commented on db/controllers/controllers.js
> +    if (Object.keys(newCommentData).length <= 1 ||
This should be handled in the model.

2023-01-19 11:12 UTC, itsaliabdallah commented on db/models/models.js
> +    return db.query(userString, [username])
this query wouldn't be needed, if you tried to add a user to the databse that didn't exist PSQL would throw an error

2023-01-19 11:17 UTC, itsaliabdallah commented on db/models/models.js
> +    return db.query(userString, [username])
this query wouldn't be needed, if you tried to add a user to the databse that didn't exist PSQL would throw an error

2023-01-19 11:20 UTC, itsaliabdallah reviewed
Really nice testing.
Just check your models where I left comments you're doing a query which wouldn't need to be done.

2023-01-19 11:45 UTC, merged